### ISSUE TITLE
Problem with data

### ISSUE THREAD

**Issue by jorge6242** [bitriddler/react-swipeable-tabs#3]
i have a problem with the example code, in chrome console :

Warning: Failed prop type: Invalid prop `items[0]` of type `object` supplied to `t`, expected a single ReactElement.
    in t (created by TestTabs)
    in TestTabs (created by BabyBar)
    in div (created by BabyBar)
    in div (created by BabyBar)
    in BabyBar (created by Header)
    in div (created by Header)
    in Header (created by Dashboard)
    in div (created by Dashboard)
    in Dashboard (created by RouterContext)
    in div (created by AppLayout)
    in AppLayout (created by Connect(AppLayout))
    in Connect(AppLayout) (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider

this error is just with the example code, help please

![captura](https://user-images.githubusercontent.com/15070448/32017806-e573d1c4-b995-11e7-87c3-b372943f8242.PNG)

**Comment by mortentz** [comment]
I am not the author of this project, but I had the same issue. I solved it by putting the divs directly into the "items" table (I used the constructor instead of componentWillMount): 
```
constructor(props) {
        super(props);
        this.state = {activeItemIndex: 0, items: [<div>Tab 1</div>, <div>Tab 2</div>, <div>Tab 3</div>, <div>Tab 4</div>]};
}
```

**Comment by jorge6242** [comment]
Hi , thanks for the help, its working fine !
